### PR TITLE
Revised State Machine Interface Class

### PR DESCRIPTION
**Pull request by marip8**
This PR replaces the existing implementation of the SCXML state machine with a new interface built off of the public `QScxml` API per the discussions in #23. Important changes include:
- Creation of function that parses the SCXML file and creates a map of states and associated transitions 
- Helper functions that check the validity of adding state callbacks and submitting events
- Removal of ROS1 and ROS2 demos.
  - They seemed to add more complexity than value
- Creation of a simple CLI demo capable of running any SCMXL state machine file
- Addition of a unit test
- Futures for asynchronous callbacks are stored in the class, and the state machine can check the status of the future before submitting an event. The submission of events can also be forced

### CODE REVIEW

**Comment by marip8** [comment]
@jrgnicho @DavidMerzJr @Levi-Armstrong can you look at this changes and let me know what you think of the proposed changes?

**Comment by Levi-Armstrong** [comment]
Will need to switch to github action to get CI back up.

**Comment by marip8** [comment]
> Will need to switch to github action to get CI back up.

I would suggest doing that as a separate PR. Travis CI works fine now. The builds succeeded, but I just don't know how to navigate to the build directory in my `AFTER_SCRIPT`. The `$target_ws` variable that we used to do this in `robot_cal_tools` doesn't seem to exist anymore

**Comment by Levi-Armstrong** [comment]
Oh, for focal CI builds the after script is not needed. Focal builds leverage colcon which runs ctests for you eliminating the need for the after script.

**Comment by marip8** [comment]
> Oh, for focal CI builds the after script is not needed. Focal builds leverage colcon which runs ctests for you eliminating the need for the after script.

I can't tell if this actually happenend. Looking at the build log, it looked like it succeeded but didn't have any output. 


Anyway, I figured out the issue with the CI script and now it's running `ctest` directly. It seems like `industrial_ci` implemented some ["hook system"](https://github.com/ros-industrial/industrial_ci/blob/7520372da8b60bb52a70cac6b24f1966f752ad83/doc/migration_guide.md#hook-system) which means that I just need to put the build path with target workspace variable in quotes: `AFTER_SCRIPT='cd $target_ws/build'` -> `AFTER_SCRIPT='cd "$target_ws/build"'`

**Comment by jrgnicho** [comment]
I think that this is so significantly different it might be better for it to live in its own repository.

**Comment by Levi-Armstrong** [comment]
> I think that this is so significantly different it might be better for it to live in its own repository.

I do not think it is necessary to have two separate repository which do the same thing. As it stands, the currently state of the repository can not be deployed because it leverages privates headers. Now if this PR solves the issue and provided the same functionality then it should be acceptable. 

I understand that project may be using this in its current state, so a tag will be created prior to merging allow those to reference the current state until they have time to upgrade. If the previous version at some point requires changes then a branch would be created to apply patches and a new release tag would be created. 

In the end the problem needs to be address leveraging the public API.

**Comment by marip8** [comment]
> I think that this is so significantly different it might be better for it to live in its own repository.

True in the sense that none of the code from the current implementation remains, yet it maintains all of the same concepts and existing functionality (except for precondition callbacks; my thoughts about these are [here](https://github.com/swri-robotics/ros_scxml/issues/23#issuecomment-756381939)). I intended this PR to be an evolution of this repository to cut dependence on the private headers. If there is some critical functionality from the current implementation that I missed, I would be happy to try to address it. I would prefer not to start a "competing" repository if possible.

This PR obviously introduces breaking changes, so I think we could tag the current version of the repository per @Levi-Armstrong 's suggestion to minimize dependency issues for those of us who are already using this repository

**Comment by jrgnicho** [comment]
> > I think that this is so significantly different it might be better for it to live in its own repository.
> 
> I do not think it is necessary to have two separate repository which do the same thing. As it stands, the currently state of the repository can not be deployed because it leverages privates headers. Now if this PR solves the issue and provided the same functionality then it should be acceptable.
> 
> I understand that project may be using this in its current state, so a tag will be created prior to merging allow those to reference the current state until they have time to upgrade. If the previous version at some point requires changes then a branch would be created to apply patches and a new release tag would be created.
> 
> In the end the problem needs to be address leveraging the public API.

If the motivation for this is to address the deployment issue then the solution to pursue here, rather than scrapping practically 100% of the code, should be to modify the build process by leveraging a combination of forward class declaration and the external project feature in cmake.  I think If there's an immediate need to have something that can be deployed then having this proposed code in a separate repository makes sense, if down the road that new repo proves to be the preferred one  then it's trivial to deprecate this one and have a link that points to the new one.

**Comment by Levi-Armstrong** [comment]
> If the motivation for this is to address the deployment issue then the solution to pursue here, rather than scrapping practically 100% of the code, should be to modify the build process by leveraging a combination of forward class declaration and the external project feature in cmake. I think If there's an immediate need to have something that can be deployed then having this proposed code in a separate repository makes sense, if down the road that new repo proves to be the preferred one then it's trivial to deprecate this one and have a link that points to the new one.

This address an issue which has been open for 6 months because it uses private headers which should not be used per Qt documentation. I am not surprised that it required such a significant change to avoid the use of the private headers. The existing state of using private headers will never be exceptionable because there is no guarantee of ABI stability of these headers.

> should be to modify the build process by leveraging a combination of forward class declaration and the external project feature in cmake.

This is a hack solution and is likely to be brittle. I proposed this as a temporary solution until someone had time to address the issue. Now that we have a viable solution it should be considered. We can push the current state to a branch for future evaluation, but if the current solution works and avoids the use of the private headers then we should make it the main solution. 

>I think If there's an immediate need to have something that can be deployed then having this proposed code in a separate repository makes sense, if down the road that new repo proves to be the preferred one then it's trivial to deprecate this one and have a link that points to the new one.

We should fix it now to avoid use of the current state on active projects.

**Comment by Levi-Armstrong** [comment]
In all honesty I have not reviewed the code to know if all of the changes were absolutely necessary or if it would be possible to have maintained parts of the existing API. I just know when I looked into this a while back there did not appear to be a way through the public API to get access to the information.

**Comment by jrgnicho** [comment]
Here is where I see the proposed implementation lacking in regards to the current one:
- The current implementation evaluates [conditional statements](https://www.w3.org/TR/scxml/#executable) defined in the scxml state machine, this feature is only accessible through the private API
- It's not clear to me if the parsing function for the transition table captures transitions inherited from the parent state.
- It's no longer possible to pass data to the state entry callbacks. 
- There doesn't appear to be a way to get output data produced by the state entry callbacks as is the case with the current implementation.
- Complete removal of precondition check callbacks, 
- I'm not sure that using qt objects in the interface (QString, QFuture, etc) is the way to go here.  My preference would be for std library objects instead as it would allow us to (in a future implementation) more easily decouple from the Qt backend if a different backend proves to be more advantageous.

**Comment by Levi-Armstrong** [comment]
>     * The current implementation evaluates [conditional statements](https://www.w3.org/TR/scxml/#executable) defined in the scxml state machine, this feature is only accessible through the private API

The Qt documentation suggest you should use [this](https://doc.qt.io/qt-5/qsignaltransition.html#details) approach to make a signal transition condition. Is there something missing from this approach?

**Comment by marip8** [comment]
>     * The current implementation evaluates [conditional statements](https://www.w3.org/TR/scxml/#executable) defined in the scxml state machine, this feature is only accessible through the private API

True. I need to look into that a little more to see if there is something I can do to support that. Per [my comment here](https://github.com/swri-robotics/ros_scxml/issues/23#issuecomment-765718694), I think it's enough in the short term to identify the transitions even if they are not valid at run time

>     * It's not clear to me if the parsing function for the transition table captures transitions inherited from the parent state.

The parsing captures inherited transitions for child states; see [this function](https://github.com/marip8/ros_scxml/blob/0de29e5d57016b9c85b4b368e0bc0d28530c78f9/scxml_core/src/scxml_sm_interface.cpp#L19-L21). You can also run the demo which prints out all available transitions for each state and visually confirm

>     * It's no longer possible to pass data to the state entry callbacks.
>     * There doesn't appear to be a way to get output data produced by the state entry callbacks as is the case with the current implementation.

True when using the pre-defined helper functions. The intent of this wrapper is to be a simple interface to the most common use-case of state machines which utilize callback functions that do not take or return any data.

If you want to store custom data in the state machine, you should use `QScxmlStateMachine` directly. It has this capability built in with its internal data model and `connectToState` function. The proposed class gives the user access to both the state map and the `QScxmlStateMachine` members. I don't think it's necessary to wrap this functionality since it's easily accessible within `QScxmlStateMachine`

I personally find it much easier to use lambdas with access to my class objects to store data rather than storing data directly in the state machine

>     * Complete removal of precondition check callbacks,

True. We could add this back in, but it seems like they are unnecessary and more or less duplicate the functionality by the conditional blocks of the SCXML format. If there is a specific compelling reason to add these back in, it would definitely be possible and pretty easy.

>     * I'm not sure that using qt objects in the interface (QString, QFuture, etc) is the way to go here.  My preference would be for std library objects instead as it would allow us to (in a future implementation) more easily decouple from the Qt backend if a different backend proves to be more advantageous.

I thought about this when I was creating this revision, and I came to the conclusion that dealing in terms of STL strings and containers involves a lot of copying to Qt strings and containers. This class is very very specific to the Qt, so I thought it was appropriate to hitch my wagon to the Qt train, so to speak. If we decided to go with a different back-end besides Qt, we would probably need to re-write all of this code anyway

**Comment by Levi-Armstrong** [comment]
> The current implementation evaluates conditional statements defined in the scxml state machine, this feature is only accessible through the private API

So I looked into the scxml state machine and I believe we are incorrectly using the library. A lot of things in Qt are data model driven and the scxml state machine uses this as a mechanism to provide customization. In the example below it shows the use of a data model. In the scxml gui you provide the conditional function `cond` to call for each of the transitions. Then in your cpp code model you provide the implementation of the function you specified in the `cond` block. This will control whether the state machine transitions. Also you specify in the gui if the transition is `external` or `internal` which determines if this transition may be triggered externally.

https://github.com/qt/qtscxml/tree/dev/examples/scxml/mediaplayer-qml-cppdatamodel

image

Then at the highest level in the gui you set the data model or it can be set using the c++ API.


> Complete removal of precondition check callbacks,

This should also be covered by the use of the code model

**Comment by Levi-Armstrong** [comment]
I believe all of the other functionality can be handled through using the data model. In the scxml gui if you right click on a state it gives you all of the onEntry, onExit, etc. You can then specify the function to be called in the data model. It also has other options like assign, cancel, log, etc. I believe the idea is you implement a data model for your process with the necessary function etc. then you just fill out the state machine using the gui. Then Qt will handle all of the connects behind the scene limiting the amount of code you need to write.

**Comment by marip8** [comment]
It would probably be beneficial to add a demo showing how to leverage the data model capability. The demo I put together (and the unit test case) were all constructed in c++ outside the SCXML file

**Comment by jrgnicho** [comment]
> > The current implementation evaluates conditional statements defined in the scxml state machine, this feature is only accessible through the private API
> 
> So I looked into the scxml state machine and I believe we are incorrectly using the library. A lot of things in Qt are data model driven and the scxml state machine uses this as a mechanism to provide customization. In the example below it shows the use of a data model. In the scxml gui you provide the conditional function `cond` to call for each of the transitions. Then in your cpp code model you provide the implementation of the function you specified in the `cond` block. This will control whether the state machine transitions. Also you specify in the gui if the transition is `external` or `internal` which determines if this transition may be triggered externally.
> 
> https://github.com/qt/qtscxml/tree/dev/examples/scxml/mediaplayer-qml-cppdatamodel
> 
> image
> 
> Then at the highest level in the gui you set the data model or it can be set using the c++ API.
> 
> > Complete removal of precondition check callbacks,
> 
> This should also be covered by the use of the code model

I think it works this way when you compile the SM from the scxml file.  We are only reading the file so I'm not sure if this operation hold true when that's the case.

**Comment by jrgnicho** [comment]
> I believe all of the other functionality can be handled through using the data model. In the scxml gui if you right click on a state it gives you all of the onEntry, onExit, etc. You can then specify the function to be called in the data model. It also has other options like assign, cancel, log, etc. I believe the idea is you implement a data model for your process with the necessary function etc. then you just fill out the state machine using the gui. Then Qt will handle all of the connects behind the scene limiting the amount of code you need to write.

Yes you can embed data in the scxml data model , I haven't used it myself but I assume that data might be limited to what can be described in xml syntax.  The original implementation allowed passing any kind of data (ros messages, custom structs, etc) and made it easily accessible to the  entry callback without having to pass a data model object around to store and retrieve data from. 
 
Furthermore, the interface was intentionally written to conceal as much of the QT event driven stuff as possible so as to lessen the burden of having to deal with minutia of event driven QT code on top of the complexities pertaining to your own application.

I think there are enough notable differences that make the proposed implementation suitable for basic cases of SM applications,  therefore to me that makes the case for having it as its own separate thing.  I'm ok if it lives alongside the current one and in the mean time we can make the build of the current implementation conditional until a proper solution to the dependency problem is found.  I don't know if a conditional build poses a problem for deployment however.

**Comment by Levi-Armstrong** [comment]
Glad to finally see this get merged in! :)

**Pull request merged**
